name: Deploy

on:
  push:
    branches:
      - convert-app-entry-point-to-use-aws

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: |
          npm install -g @vercel/ncc
          ncc build index.ts -o dist

      - name: Update Lambda Environment Variables
        run: |
          aws lambda update-function-configuration \
            --function-name lambda-gh-action \
            --environment "Variables={MONGO_URI=${{ secrets.MONGO_URI }}}"

      - name: Create deployment package
        run: |
          cd dist
          zip -r ../deploy.zip ./*

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name lambda-gh-action \
            --zip-file fileb://deploy.zip
